# Generated by Django 4.2.2 on 2023-06-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_color', models.CharField(max_length=50)),
                ('model', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback')], max_length=50)),
                ('brand', models.CharField(choices=[('toyota', 'Toyota'), ('ford', 'Ford'), ('chevrolet', 'Chevrolet'), ('honda', 'Honda')], max_length=50)),
                ('value', models.IntegerField()),
                ('production_costs', models.IntegerField()),
                ('transportation_costs', models.IntegerField()),
            ],
        ),
    ]
